export const NETWORK_COUNTS = {
  total: 24,
  trainingProviders: 15,
  backbone: 4,
  employmentLiaisons: 5,
} as const;

export const BACKBONES = [
  { id: 16, name: "Piedmont-Triad Workforce Board" },
  { id: 17, name: "Capital Area Workforce Development" },
  { id: 18, name: "Eastern Carolina Workforce Consortium" },
  { id: 19, name: "Western NC Skills Partnership" },
] as const;

export const EMPLOYMENT_LIAISONS = [
  { id: 20, name: "NorthStar Career Network" },
  { id: 21, name: "Horizon Job Connect" },
  { id: 22, name: "Coastal Employer Alliance" },
  { id: 23, name: "Mountain Pathways Liaison" },
  { id: 24, name: "Metro Talent Bridge" },
] as const;

export type TrainingProviderOrg = {
  id: number;
  name: string;
  backbone: string | null;
  code: string;
  program: string;
  region: string;
  enrolled: number;
  completed: number;
  placed: number;
};

export const TRAINING_PROVIDERS: TrainingProviderOrg[] = [
  {
    id: 1,
    name: "Piedmont Community College",
    backbone: "Piedmont-Triad Workforce Board",
    code: "TP-017",
    program: "Advanced Manufacturing",
    region: "Central region",
    enrolled: 18,
    completed: 10,
    placed: 7,
  },
  {
    id: 2,
    name: "Triad Workforce Alliance",
    backbone: "Piedmont-Triad Workforce Board",
    code: "TP-009",
    program: "Healthcare Pathways",
    region: "Triad region",
    enrolled: 24,
    completed: 18,
    placed: 14,
  },
  {
    id: 3,
    name: "Central Carolina Skills",
    backbone: "Capital Area Workforce Development",
    code: "TP-021",
    program: "IT Support",
    region: "Central region",
    enrolled: 12,
    completed: 6,
    placed: 3,
  },
  {
    id: 4,
    name: "Durham Technical Institute",
    backbone: "Capital Area Workforce Development",
    code: "TP-004",
    program: "Allied Health",
    region: "Triangle region",
    enrolled: 16,
    completed: 9,
    placed: 6,
  },
  {
    id: 5,
    name: "Fayetteville Career Academy",
    backbone: "Capital Area Workforce Development",
    code: "TP-011",
    program: "Logistics",
    region: "Sandhills region",
    enrolled: 14,
    completed: 8,
    placed: 5,
  },
  {
    id: 6,
    name: "Guilford Workforce College",
    backbone: "Piedmont-Triad Workforce Board",
    code: "TP-014",
    program: "Welding",
    region: "Triad region",
    enrolled: 11,
    completed: 7,
    placed: 4,
  },
  {
    id: 7,
    name: "Cape Fear Skills Center",
    backbone: "Eastern Carolina Workforce Consortium",
    code: "TP-008",
    program: "Construction Trades",
    region: "Coastal region",
    enrolled: 13,
    completed: 8,
    placed: 6,
  },
  {
    id: 8,
    name: "Asheville Trades Institute",
    backbone: "Western NC Skills Partnership",
    code: "TP-002",
    program: "HVAC",
    region: "Western region",
    enrolled: 10,
    completed: 5,
    placed: 4,
  },
  {
    id: 9,
    name: "Charlotte Advanced Manufacturing Hub",
    backbone: "Capital Area Workforce Development",
    code: "TP-019",
    program: "CNC Machining",
    region: "Metro region",
    enrolled: 22,
    completed: 15,
    placed: 11,
  },
  {
    id: 10,
    name: "Winston Health Pathways",
    backbone: "Piedmont-Triad Workforce Board",
    code: "TP-023",
    program: "CNA to LPN",
    region: "Triad region",
    enrolled: 19,
    completed: 12,
    placed: 9,
  },
  {
    id: 11,
    name: "Greenville IT Academy",
    backbone: "Eastern Carolina Workforce Consortium",
    code: "TP-006",
    program: "Cybersecurity",
    region: "Eastern region",
    enrolled: 15,
    completed: 9,
    placed: 7,
  },
  {
    id: 12,
    name: "Wilmington Marine Trades",
    backbone: "Eastern Carolina Workforce Consortium",
    code: "TP-027",
    program: "Marine Maintenance",
    region: "Coastal region",
    enrolled: 9,
    completed: 4,
    placed: 3,
  },
  {
    id: 13,
    name: "High Point Furniture Skills",
    backbone: "Western NC Skills Partnership",
    code: "TP-012",
    program: "Production Operations",
    region: "Triad region",
    enrolled: 8,
    completed: 5,
    placed: 4,
  },
  {
    id: 14,
    name: "Rocky Mount Logistics College",
    backbone: "Eastern Carolina Workforce Consortium",
    code: "TP-031",
    program: "Supply Chain",
    region: "Eastern region",
    enrolled: 12,
    completed: 6,
    placed: 5,
  },
  {
    id: 15,
    name: "Hickory Engineering Prep",
    backbone: "Western NC Skills Partnership",
    code: "TP-016",
    program: "Industrial Maintenance",
    region: "Western region",
    enrolled: 11,
    completed: 6,
    placed: 4,
  },
];
